import { addCollection } from '@iconify/vue'
import { icons as materialIconTheme } from '@iconify-json/material-icon-theme'

addCollection(materialIconTheme)

const PREFIX = 'material-icon-theme'

const FOLDER_BY_NAME: Record<string, string> = {
  src: 'folder-src',
  source: 'folder-src',
  sources: 'folder-src',
  composables: 'folder-hook',
  hooks: 'folder-hook',
  hook: 'folder-hook',
  config: 'folder-config',
  configs: 'folder-config',
  configuration: 'folder-config',
  settings: 'folder-config',
  '.config': 'folder-config',
  extensions: 'folder-plugin',
  plugins: 'folder-plugin',
  plugin: 'folder-plugin',
  layouts: 'folder-layout',
  layout: 'folder-layout',
  locales: 'folder-i18n',
  locale: 'folder-i18n',
  i18n: 'folder-i18n',
  lang: 'folder-i18n',
  langs: 'folder-i18n',
  languages: 'folder-i18n',
  router: 'folder-routes',
  routers: 'folder-routes',
  routes: 'folder-routes',
  route: 'folder-routes',
  services: 'folder-api',
  service: 'folder-api',
  api: 'folder-api',
  apis: 'folder-api',
  styles: 'folder-css',
  style: 'folder-css',
  css: 'folder-css',
  scss: 'folder-sass',
  sass: 'folder-sass',
  less: 'folder-less',
  types: 'folder-typescript',
  typings: 'folder-typescript',
  typescript: 'folder-typescript',
  '@types': 'folder-typescript',
  components: 'folder-components',
  component: 'folder-components',
  views: 'folder-views',
  view: 'folder-views',
  pages: 'folder-views',
  page: 'folder-views',
  utils: 'folder-utils',
  util: 'folder-utils',
  helpers: 'folder-helper',
  helper: 'folder-helper',
  lib: 'folder-lib',
  libs: 'folder-lib',
  library: 'folder-lib',
  libraries: 'folder-lib',
  assets: 'folder-images',
  images: 'folder-images',
  img: 'folder-images',
  icons: 'folder-images',
  public: 'folder-public',
  static: 'folder-resource',
  resources: 'folder-resource',
  resource: 'folder-resource',
  tests: 'folder-test',
  test: 'folder-test',
  __tests__: 'folder-test',
  spec: 'folder-test',
  specs: 'folder-test',
  e2e: 'folder-test',
  store: 'folder-store',
  stores: 'folder-store',
  pinia: 'folder-vuex-store',
  vuex: 'folder-vuex-store',
  middleware: 'folder-middleware',
  middlewares: 'folder-middleware',
  constants: 'folder-constant',
  constant: 'folder-constant',
  models: 'folder-database',
  model: 'folder-database',
  schemas: 'folder-database',
  schema: 'folder-database',
  db: 'folder-database',
  database: 'folder-database',
  controllers: 'folder-controller',
  controller: 'folder-controller',
  interfaces: 'folder-interface',
  interface: 'folder-interface',
  scripts: 'folder-scripts',
  script: 'folder-scripts',
  dist: 'folder-dist',
  build: 'folder-dist',
  out: 'folder-dist',
  output: 'folder-dist',
  node_modules: 'folder-node',
  vendor: 'folder-node',
  '.git': 'folder-git',
  '.github': 'folder-github',
  '.vscode': 'folder-vscode',
  '.idea': 'folder-intellij',
  docker: 'folder-docker',
  docs: 'folder-docs',
  doc: 'folder-docs',
  documentation: 'folder-docs',
  examples: 'folder-examples',
  example: 'folder-examples',
  demo: 'folder-examples',
  temp: 'folder-temp',
  tmp: 'folder-temp',
  cache: 'folder-temp',
  logs: 'folder-log',
  log: 'folder-log',
  ci: 'folder-ci',
  '.circleci': 'folder-circleci',
  kubernetes: 'folder-kubernetes',
  k8s: 'folder-kubernetes',
  terraform: 'folder-terraform',
  ansible: 'folder-ansible',
  android: 'folder-android',
  ios: 'folder-ios',
  mobile: 'folder-mobile',
  desktop: 'folder-desktop',
  shared: 'folder-shared',
  common: 'folder-shared',
  core: 'folder-core',
  app: 'folder-app',
  apps: 'folder-app',
  server: 'folder-server',
  backend: 'folder-server',
  client: 'folder-client',
  frontend: 'folder-client',
  chat: 'folder-messages',
  functions: 'folder-functions',
  tools: 'folder-tools',
  fonts: 'folder-font',
  font: 'folder-font',
  themes: 'folder-theme',
  theme: 'folder-theme',
  mocks: 'folder-mock',
  mock: 'folder-mock',
  cypress: 'folder-cypress',
  storybook: 'folder-storybook',
  stories: 'folder-storybook',
  python: 'folder-python',
  java: 'folder-java',
  go: 'folder-go',
  rust: 'folder-rust',
  php: 'folder-php',
  vue: 'folder-vue',
  astro: 'folder-astro',
  next: 'folder-next',
  nuxt: 'folder-nuxt',
  ide: 'folder-app',
  agent: 'folder-app',
}

const FILE_BY_EXT: Record<string, string> = {
  ts: 'typescript',
  mts: 'typescript',
  cts: 'typescript',
  tsx: 'react',
  js: 'javascript',
  mjs: 'javascript',
  cjs: 'javascript',
  jsx: 'react',
  vue: 'vue',
  json: 'json',
  jsonc: 'json',
  json5: 'json',
  md: 'markdown',
  mdx: 'markdown',
  py: 'python',
  pyi: 'python',
  go: 'go',
  rs: 'rust',
  java: 'java',
  kt: 'kotlin',
  kts: 'kotlin',
  php: 'php',
  rb: 'ruby',
  c: 'c',
  h: 'c',
  cpp: 'cpp',
  cc: 'cpp',
  cxx: 'cpp',
  hpp: 'cpp',
  cs: 'csharp',
  swift: 'swift',
  html: 'html',
  htm: 'html',
  xml: 'xml',
  svg: 'svg',
  css: 'css',
  scss: 'sass',
  sass: 'sass',
  less: 'less',
  styl: 'stylus',
  yaml: 'yaml',
  yml: 'yaml',
  toml: 'toml',
  graphql: 'graphql',
  gql: 'graphql',
  prisma: 'prisma',
  proto: 'proto',
  sql: 'database',
  sh: 'console',
  bash: 'console',
  zsh: 'console',
  fish: 'console',
  ps1: 'powershell',
  png: 'image',
  jpg: 'image',
  jpeg: 'image',
  gif: 'image',
  webp: 'image',
  ico: 'favicon',
  bmp: 'image',
  avif: 'image',
  pdf: 'pdf',
  doc: 'word',
  docx: 'word',
  xls: 'table',
  xlsx: 'table',
  csv: 'table',
  zip: 'zip',
  gz: 'zip',
  tar: 'zip',
  tgz: 'zip',
  '7z': 'zip',
  rar: 'zip',
  log: 'log',
  lock: 'lock',
  wasm: 'exe',
  exe: 'exe',
  dll: 'dll',
  woff: 'font',
  woff2: 'font',
  ttf: 'font',
  otf: 'font',
  eot: 'font',
  mp3: 'audio',
  wav: 'audio',
  mp4: 'video',
  webm: 'video',
  diff: 'diff',
  patch: 'diff',
  key: 'key',
  pem: 'key',
  crt: 'certificate',
  cer: 'certificate',
}

const FILE_BY_NAME: Record<string, string> = {
  'package.json': 'npm',
  'package-lock.json': 'npm',
  'npm-shrinkwrap.json': 'npm',
  '.npmrc': 'npm',
  'yarn.lock': 'yarn',
  '.yarnrc': 'yarn',
  '.yarnrc.yml': 'yarn',
  'pnpm-lock.yaml': 'pnpm',
  'pnpm-workspace.yaml': 'pnpm',
  '.pnpmfile.cjs': 'pnpm',
  'tsconfig.json': 'tsconfig',
  'jsconfig.json': 'jsconfig',
  'vite.config.ts': 'vite',
  'vite.config.js': 'vite',
  'vite.config.mts': 'vite',
  'vitest.config.ts': 'vitest',
  'vitest.config.js': 'vitest',
  'eslint.config.js': 'eslint',
  'eslint.config.ts': 'eslint',
  'eslint.config.mjs': 'eslint',
  '.eslintrc': 'eslint',
  '.eslintrc.js': 'eslint',
  '.eslintrc.cjs': 'eslint',
  '.eslintrc.json': 'eslint',
  '.prettierrc': 'prettier',
  '.prettierrc.js': 'prettier',
  '.prettierrc.json': 'prettier',
  '.prettierrc.yaml': 'prettier',
  'prettier.config.js': 'prettier',
  'readme.md': 'readme',
  'readme': 'readme',
  license: 'license',
  'license.md': 'license',
  dockerfile: 'docker',
  'docker-compose.yml': 'docker',
  'docker-compose.yaml': 'docker',
  '.dockerignore': 'docker',
  '.gitignore': 'git',
  '.gitattributes': 'git',
  '.gitmodules': 'git',
  makefile: 'makefile',
  'cmakelists.txt': 'cmake',
  '.editorconfig': 'editorconfig',
  '.nvmrc': 'nodejs',
  '.node-version': 'nodejs',
  'tailwind.config.js': 'tailwindcss',
  'tailwind.config.ts': 'tailwindcss',
  'postcss.config.js': 'postcss',
  'postcss.config.cjs': 'postcss',
  'jest.config.js': 'jest',
  'jest.config.ts': 'jest',
  'playwright.config.ts': 'playwright',
  'cypress.config.ts': 'cypress',
  'webpack.config.js': 'webpack',
  'rollup.config.js': 'rollup',
  'babel.config.js': 'babel',
  '.babelrc': 'babel',
  'schema.prisma': 'prisma',
  'nginx.conf': 'nginx',
  'robots.txt': 'robots',
  favicon: 'favicon',
  'favicon.ico': 'favicon',
}

function withPrefix(name: string): string {
  return `${PREFIX}:${name}`
}

export function resolveFileTreeIcon(
  kind: 'file' | 'dir',
  path: string,
  expanded = false,
): string {
  const name = path.split('/').filter(Boolean).pop()?.toLowerCase() ?? ''
  if (kind === 'dir') {
    const folder = FOLDER_BY_NAME[name] ?? 'folder-other'
    return withPrefix(expanded ? `${folder}-open` : folder)
  }
  if (FILE_BY_NAME[name]) return withPrefix(FILE_BY_NAME[name])
  if (name.startsWith('.env')) return withPrefix('tune')
  if (name.startsWith('tsconfig.') && name.endsWith('.json')) return withPrefix('tsconfig')
  if (name.startsWith('docker-compose')) return withPrefix('docker')
  if (name.startsWith('vite.config.')) return withPrefix('vite')
  if (name.startsWith('vitest.config.')) return withPrefix('vitest')
  const ext = name.includes('.') ? name.split('.').pop() ?? '' : ''
  return withPrefix(FILE_BY_EXT[ext] ?? 'document')
}
